WARNING: added an empty peerDependency to package.json, which seems wierd, to fix the following:
 tsc && vite build

▲ [WARNING] Import "peerDependencies" will always be undefined because there is no matching export in "package.json" [import-is-undefined]

    vite.config.ts:25:44:
      25 │       external: [...Object.keys(packageJson.peerDependencies)],
         ╵                                             ~~~~~~~~~~~~~~~~

The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
failed to load config from /Users/klas.mellbourn/code/dmaze/sharing/earthly-npm-workspaces-monorepo/packages/components/vite.config.ts
error during build:
TypeError: Cannot convert undefined or null to object